print("heloo bruh !")
a = str(input("Enter A String : "))
a2 = len(a)
print("The length o the string is : ",a2)
length = int(a2 / 2)
print("The First Half of the string is :- ")
print(a[0:length])
print("the second half of the string is :- ")
print(a[length:])
